### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by tunelko** [tonyseek/openvpn-status#12]
Hi, 
With your own example, keyerror on retrieving status.client_list["foo@example.com"]

Debugging on pdb 
`--Return--
> /usr/local/lib/python3.5/dist-packages/openvpn_status/descriptors.py(19)__get__()->OrderedDict([...6d9e2d77f0>)])
-> return instance.__dict__[self.__name__]
(Pdb)
KeyError: 'foo@example.com'
`
But if i try to set "Real Address" field, it works in your example. 

I'll continue trying to catch the error and post here. Could you review ? 
Thanks.

**Comment by tonyseek** [comment]
Hi @tunelko,

It is a breaking change in [0.2.0](https://github.com/tonyseek/openvpn-status/blob/b8f5ec5f79933605af2301c42e4e7ec230334237/CHANGES.rst#020-2017-10-20). The `status.client_list` is indexed by the `client.real_address` instead of `client.common_name` because `common_name` is not unique while multiple sessions on the same user (https://github.com/tonyseek/openvpn-status/issues/2 https://github.com/tonyseek/openvpn-status/pull/5).

The document and README file is staled. I will update them soon.

Thank you for your feedback!
